[package]
name = "maschinengott"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced-x86 = "1.17.0"
colored = "2.0.0"
exe = "0.5.4"
structopt = "0.3.26"
rayon = "1.5.3"
